sudo: required
language: bash
services:
  - docker

before_script:
  - docker -v
  - docker build . --tag=xls2cvs-processor
  - docker run my-component /bin/bash -c "composer install --no-interaction --no-progress && composer ci"

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
