sudo: required
language: bash
services:
  - docker

before_script:
  - docker -v

script:
  - docker build -t xls2cvs-processor .
  - docker run xls2cvs-processor /bin/bash -c "composer install --no-interaction --no-progress && composer ci"

after_success:
  - docker images
  - ./release.sh

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$
